### ISSUE TITLE
Allow to parameterize delimiters

### ISSUE THREAD

**Issue by garciparedes** [vberlier/extract-math#46]
As proposed on https://github.com/garciparedes/ng-katex/issues/532, it would be an interesting feature being able to set custom delimiters instead of forcing to always use `$` and `$$` for `inline` and `display` respectively.

**Comment by garciparedes** [comment]
Hi @vberlier! I'll proceed to resolve this issue and pull request a change to allow that behaviour.

**Comment by vberlier** [comment]
Hello! I apologize I had to take a break to work on other things, I just published a version that makes it possible to specify custom delimiters.

And thanks for the pull request. I would've merged it as is but I wanted to provide a different API. It still helped me a lot to test things out and get it done quickly though, so it was much appreciated :+1:
